### ISSUE TITLE
Avoid [0:0] for 1-bit signals

### ISSUE THREAD

**Issue by mksoc** [HEP-SoC/PeakRDL-socgen#1]

**Comment by Risto97** [comment]
Hello Marco, Thank you for making the repository open-source.

I just wanted to give you my justification as to why I kept `[0:0]` for single-bit signals.

I decided not to optimize the syntax of single-bit signals, as it increases the complexity of template files, without providing improvement to generated code other than slight aesthetic improvement.

Since now at every signal declaration, you need to have an `if` clause to check for signal width.
I agree that one optimization is not a big deal, however as more aesthetic optimizations are added, they will obfuscate the real intent of the template code, making it harder to understand and maintain.

I am talking from experience on a similar code generator, where authors tried to handle almost every aesthetic improvement in the generating logic, where the real intent got buried deep in `if` clauses.

```diff
-{{ s.verilogDir }} [{{ s.width-1 }}:0] {{ s.name }}{% if (not loop.last) or (subsys.ports|length > 0) %},{% endif %}
+{{ s.verilogDir }}{% if s.width > 1 %} [{{ s.width -1 }}:0]{% endif %} {{ s.name }}{% if (not loop.last) or (subsys.ports|length > 0) %},{% endif %}
```

I am sure you had a valid reason for a change, I just wanted to give you a tip that the maintainability of the python and template code, is probably more important long term than small optimizations.

**Comment by mksoc** [comment]
Hi Risto! Thanks for your input. I feel in this particular case the change was small enough not to impact the readability of the template too much, but yes, it was just for aesthetic reasons and it's debatable. I will keep in mind though what you said, so that we don't get too deep in adding ifs for formatting stuff.
